name = "CMSCertificationNumbers"
uuid = "dd30a495-ddaa-4e90-b4c8-e67bdf9f6075"
authors = ["Phil Killewald <reallyasi9@users.noreply.github.com> and contributors"]
version = "1.0.0"

[deps]
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"

[compat]
InlineStrings = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
